USE [master]
GO
/****** Object:  Database [ClubFutbol_DB]    Script Date: 19/6/2022 21:22:29 ******/
CREATE DATABASE [ClubFutbol_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ClubFutbol_DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER04\MSSQL\DATA\ClubFutbol_DB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ClubFutbol_DB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER04\MSSQL\DATA\ClubFutbol_DB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [ClubFutbol_DB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ClubFutbol_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ClubFutbol_DB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ClubFutbol_DB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ClubFutbol_DB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ClubFutbol_DB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ClubFutbol_DB] SET ARITHABORT OFF 
GO
ALTER DATABASE [ClubFutbol_DB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ClubFutbol_DB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ClubFutbol_DB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ClubFutbol_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ClubFutbol_DB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ClubFutbol_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ClubFutbol_DB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ClubFutbol_DB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ClubFutbol_DB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ClubFutbol_DB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ClubFutbol_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ClubFutbol_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ClubFutbol_DB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ClubFutbol_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ClubFutbol_DB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ClubFutbol_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ClubFutbol_DB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ClubFutbol_DB] SET RECOVERY FULL 
GO
ALTER DATABASE [ClubFutbol_DB] SET  MULTI_USER 
GO
ALTER DATABASE [ClubFutbol_DB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ClubFutbol_DB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ClubFutbol_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ClubFutbol_DB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ClubFutbol_DB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ClubFutbol_DB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'ClubFutbol_DB', N'ON'
GO
ALTER DATABASE [ClubFutbol_DB] SET QUERY_STORE = OFF
GO
USE [ClubFutbol_DB]
GO
/****** Object:  Table [dbo].[Estadisticas]    Script Date: 19/6/2022 21:22:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Estadisticas](
	[FECHA] [date] NOT NULL,
	[CANT_JUGADORES] [int] NOT NULL,
	[CANT_PARTIDOS] [int] NOT NULL,
	[CANT_GOLES] [int] NOT NULL,
	[CANT_ASISTENCIAS] [int] NOT NULL,
	[PROM_GOLES] [float] NOT NULL,
	[PROM_ASISTENCIAS] [float] NOT NULL,
	[PORCENTAJE_ARQUERO] [float] NOT NULL,
	[PORCENTAJE_DEFENSOR] [float] NOT NULL,
	[PORCENTAJE_MEDIOCAMPISTA] [float] NOT NULL,
	[PORCENTAJE_DELANTERO] [float] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Jugadores]    Script Date: 19/6/2022 21:22:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Jugadores](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DNI] [varchar](50) NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[APELLIDO] [varchar](50) NOT NULL,
	[FECHA_INGRESO] [date] NOT NULL,
	[POSICION] [varchar](50) NOT NULL,
	[ESTA_ACTIVO] [bit] NOT NULL,
 CONSTRAINT [PK_Jugadores] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [ClubFutbol_DB] SET  READ_WRITE 
GO

--1 activo / 0 inactivo--
INSERT INTO Jugadores (DNI, NOMBRE, APELLIDO, FECHA_INGRESO, POSICION, ESTA_ACTIVO)     
VALUES 
('41235224', 'Ramiro', 'Olicino', '2021-08-21', 'Arquero', 1),
('41235321', 'Juan', 'Ramirez', '2020-05-18', 'Arquero', 1),
('41235645', 'Ricardo', 'Ramirez', '2019-08-15', 'Defensor', 1),
('41235756', 'Martin', 'Perez', '2021-01-18', 'Defensor', 1),
('41235567', 'Ignacio', 'Gonzales', '2021-05-08', 'Defensor', 1),
('41235987', 'Nicolas', 'Bufi', '2021-11-22', 'Defensor', 1),
('41235890', 'David', 'Shargo', '2018-02-10', 'Mediocampista', 1),
('42235224', 'Matias', 'Gorini', '2019-09-12', 'Mediocampista', 1),
('43235224', 'Patricio', 'Olivia', '2021-02-10', 'Mediocampista', 1),
('41312224', 'Francisco', 'Olicino', '2022-01-01', 'Mediocampista', 1),
('41123224', 'Gonzalo', 'Pirez', '2021-12-12', 'Mediocampista', 1),
('41276524', 'David', 'Molinas', '2022-02-10', 'Mediocampista', 1),
('41265424', 'Ariel', 'Mansat', '2021-08-10', 'Delantero', 1),
('39235224', 'Anel', 'Mansat', '2021-08-17', 'Delantero', 1),
('38235224', 'Jorge', 'Escobar', '2018-08-10', 'Delantero', 1),
('41423550', 'Nacho', 'Milesi', '2021-08-10', 'Delantero', 1),
('48235224', 'Nicolas', 'Mancusso', '2019-03-17', 'Delantero', 1),
('50235224', 'Ramiro', 'Arjona', '2015-08-10', 'Defensor', 0),
('41235001', 'Luis', 'Occhio', '2017-12-12', 'Mediocampista', 0),
('41235877', 'Martin', 'Antuan', '2017-05-10', 'Defensor', 0);
